defaults:
  - env: reach_env # environment to use
  - reward: reward # reward function to use
  - algo: sac # algorithm to use
  - experiment: default_run # experiment configuration to use
  - _self_

seed: 42
video_dump: true
checkpoint_path : null
wandb:
  project: "isaaclab_franka_suite"
  entity: "vladimirgharagulyan-mu-leoben" # replace with your W&B entity
  mode: "online"
