defaults:
  - env: reach_env
  - reward: reward
  - algo: sac
  - experiment: default_run
  - _self_

seed: 42
video_dump: true
checkpoint_path : null
wandb:
  project: "isaaclab_franka_suite"
  entity: "vladimirgharagulyan-mu-leoben" # replace with your W&B entity
  mode: "online"
